/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyPlanRouteImport } from './routes/study-plan'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AppliedRouteImport } from './routes/applied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ApiPublicHooksScrapeJobsRouteImport } from './routes/api/public/hooks/scrape-jobs'

const StudyPlanRoute = StudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppliedRoute = AppliedRouteImport.update({
  id: '/applied',
  path: '/applied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScrapeJobsRoute =
  ApiPublicHooksScrapeJobsRouteImport.update({
    id: '/api/public/hooks/scrape-jobs',
    path: '/api/public/hooks/scrape-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applied': typeof AppliedRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/resume': typeof ResumeRoute
  '/study-plan': typeof StudyPlanRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/api/public/hooks/scrape-jobs': typeof ApiPublicHooksScrapeJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applied': typeof AppliedRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/resume': typeof ResumeRoute
  '/study-plan': typeof StudyPlanRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/api/public/hooks/scrape-jobs': typeof ApiPublicHooksScrapeJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applied': typeof AppliedRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/resume': typeof ResumeRoute
  '/study-plan': typeof StudyPlanRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/api/public/hooks/scrape-jobs': typeof ApiPublicHooksScrapeJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applied'
    | '/bookmarks'
    | '/dashboard'
    | '/login'
    | '/recommendations'
    | '/resume'
    | '/study-plan'
    | '/jobs/$jobId'
    | '/api/public/hooks/scrape-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applied'
    | '/bookmarks'
    | '/dashboard'
    | '/login'
    | '/recommendations'
    | '/resume'
    | '/study-plan'
    | '/jobs/$jobId'
    | '/api/public/hooks/scrape-jobs'
  id:
    | '__root__'
    | '/'
    | '/applied'
    | '/bookmarks'
    | '/dashboard'
    | '/login'
    | '/recommendations'
    | '/resume'
    | '/study-plan'
    | '/jobs/$jobId'
    | '/api/public/hooks/scrape-jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppliedRoute: typeof AppliedRoute
  BookmarksRoute: typeof BookmarksRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ResumeRoute: typeof ResumeRoute
  StudyPlanRoute: typeof StudyPlanRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ApiPublicHooksScrapeJobsRoute: typeof ApiPublicHooksScrapeJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-plan': {
      id: '/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof StudyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applied': {
      id: '/applied'
      path: '/applied'
      fullPath: '/applied'
      preLoaderRoute: typeof AppliedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-jobs': {
      id: '/api/public/hooks/scrape-jobs'
      path: '/api/public/hooks/scrape-jobs'
      fullPath: '/api/public/hooks/scrape-jobs'
      preLoaderRoute: typeof ApiPublicHooksScrapeJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppliedRoute: AppliedRoute,
  BookmarksRoute: BookmarksRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RecommendationsRoute: RecommendationsRoute,
  ResumeRoute: ResumeRoute,
  StudyPlanRoute: StudyPlanRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ApiPublicHooksScrapeJobsRoute: ApiPublicHooksScrapeJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
